In [1]:
import cv2
import numpy as np 


In [2]:
import imutils
import cv2
from imutils.video import VideoStream, FileVideoStream
import time
import numpy as np

# Load the model
modelFile = "../models/res10_300x300_ssd_iter_140000.caffemodel"
configFile = "../models/deploy.prototxt.txt"
net = cv2.dnn.readNetFromCaffe(configFile, modelFile)
confidence_threshold = .7

# To capture video from webcam. 
vs = VideoStream(src=0).start()
time.sleep(2.0)
# To use a video file as input 
# vs = FileVideoStream('../data/cohface/1/0/data.avi').start()

while True:
    # grab frame and resize
    frame = vs.read()
    frame = imutils.resize(frame, width=400)
    # grab the frame dimensions and convert it to a blob
    (h, w) = frame.shape[:2]
    blob = cv2.dnn.blobFromImage(cv2.resize(frame, (300, 300)), 1.0,
        (300, 300), (104.0, 177.0, 123.0))
    # pass the blob through the network and obtain the detections and
    # predictions
    net.setInput(blob)
    detections = net.forward()
    for i in range(0, detections.shape[2]):
        # extract the confidence (i.e., probability) associated with the
        # prediction
        confidence = detections[0, 0, i, 2]
        # filter out weak detections by ensuring the `confidence` is
        # greater than the minimum confidence
        if confidence < confidence_threshold:
            continue
        # compute the (x, y)-coordinates of the bounding box for the
        # object
        box = detections[0, 0, i, 3:7] * np.array([w, h, w, h])
        (startX, startY, endX, endY) = box.astype("int")
 
        # draw the bounding box of the face along with the associated
        # probability
        text = "{:.2f}%".format(confidence * 100)
        y = startY - 10 if startY - 10 > 10 else startY + 10
        cv2.rectangle(frame, (startX, startY), (endX, endY),
            (0, 0, 255), 2)
        cv2.putText(frame, text, (startX, y),
            cv2.FONT_HERSHEY_SIMPLEX, 0.45, (0, 0, 255), 2)
        
    # show the output frame
    cv2.imshow("Frame", frame)
    key = cv2.waitKey(1) & 0xFF
 
    # if the `q` key was pressed, break from the loop
    if key == ord("q"):
        break
# do a bit of cleanup
cv2.destroyAllWindows()
vs.stop()

[[[ 96 114 129]
  [ 97 115 130]
  [ 95 112 130]
  ...
  [162 168 176]
  [162 168 176]
  [161 167 175]]

 [[ 97 113 126]
  [ 97 113 126]
  [ 99 115 129]
  ...
  [161 170 177]
  [160 169 176]
  [159 167 175]]

 [[101 115 129]
  [ 99 113 126]
  [ 98 112 125]
  ...
  [160 169 176]
  [160 169 176]
  [159 167 175]]

 ...

 [[ 37  29  35]
  [ 39  30  36]
  [ 37  29  35]
  ...
  [ 43  35  59]
  [ 41  33  55]
  [ 41  33  55]]

 [[ 33  27  32]
  [ 35  29  35]
  [ 37  30  36]
  ...
  [ 42  36  62]
  [ 41  35  61]
  [ 40  33  59]]

 [[ 35  25  34]
  [ 36  27  35]
  [ 34  28  33]
  ...
  [ 42  36  60]
  [ 42  36  62]
  [ 42  36  62]]]
[[[ 97 114 128]
  [ 97 113 129]
  [ 97 114 129]
  ...
  [160 167 175]
  [161 168 176]
  [161 168 175]]

 [[ 99 114 127]
  [ 99 113 126]
  [100 115 128]
  ...
  [159 168 175]
  [160 169 176]
  [159 168 175]]

 [[ 98 114 125]
  [100 115 126]
  [100 115 127]
  ...
  [160 169 176]
  [161 170 177]
  [160 169 176]]

 ...

 [[ 40  32  39]
  [ 38  29  36]
  [ 36  26  35]
  ..

[[[ 97 114 125]
  [ 98 115 126]
  [ 98 114 128]
  ...
  [159 167 175]
  [159 167 175]
  [159 167 175]]

 [[ 99 115 129]
  [ 99 115 129]
  [100 114 128]
  ...
  [155 164 172]
  [161 167 175]
  [162 168 176]]

 [[ 99 115 129]
  [ 98 114 128]
  [102 117 133]
  ...
  [160 169 176]
  [159 167 175]
  [160 169 176]]

 ...

 [[ 40  30  39]
  [ 39  29  37]
  [ 37  28  36]
  ...
  [ 44  35  62]
  [ 43  34  61]
  [ 44  35  62]]

 [[ 42  32  42]
  [ 37  27  38]
  [ 37  29  37]
  ...
  [ 44  35  55]
  [ 42  34  58]
  [ 42  34  58]]

 [[ 35  25  34]
  [ 34  24  33]
  [ 37  28  36]
  ...
  [ 43  35  52]
  [ 46  37  59]
  [ 40  31  53]]]
[[[ 98 115 127]
  [ 98 114 127]
  [ 98 113 127]
  ...
  [160 168 176]
  [158 166 174]
  [160 167 175]]

 [[ 99 115 129]
  [100 115 130]
  [ 99 114 129]
  ...
  [162 169 177]
  [159 168 175]
  [161 168 176]]

 [[101 115 129]
  [100 115 128]
  [100 116 129]
  ...
  [161 167 175]
  [162 168 176]
  [162 169 176]]

 ...

 [[ 39  29  36]
  [ 36  28  36]
  [ 34  24  34]
  ..

[[[ 96 114 129]
  [ 97 115 130]
  [ 99 115 130]
  ...
  [160 168 178]
  [160 169 176]
  [160 169 176]]

 [[101 116 131]
  [101 116 131]
  [ 97 116 129]
  ...
  [160 169 176]
  [160 169 176]
  [161 170 177]]

 [[ 96 111 127]
  [ 98 113 129]
  [ 98 113 129]
  ...
  [159 167 175]
  [160 169 176]
  [163 172 180]]

 ...

 [[ 35  29  35]
  [ 35  29  35]
  [ 37  29  35]
  ...
  [ 45  35  57]
  [ 45  35  57]
  [ 43  33  55]]

 [[ 35  29  35]
  [ 35  29  35]
  [ 39  30  36]
  ...
  [ 43  37  56]
  [ 43  34  54]
  [ 42  33  52]]

 [[ 37  27  38]
  [ 36  26  37]
  [ 40  30  39]
  ...
  [ 44  38  57]
  [ 46  37  59]
  [ 45  35  57]]]
[[[ 98 115 130]
  [ 98 115 130]
  [ 98 114 129]
  ...
  [160 168 178]
  [160 169 177]
  [160 169 176]]

 [[ 98 113 129]
  [ 98 114 129]
  [ 98 116 130]
  ...
  [161 169 177]
  [160 168 176]
  [161 170 178]]

 [[ 99 114 130]
  [ 99 116 131]
  [101 116 132]
  ...
  [160 170 176]
  [160 168 176]
  [160 169 176]]

 ...

 [[ 39  29  37]
  [ 38  28  35]
  [ 38  27  35]
  ..

[[[ 96 114 129]
  [ 95 113 128]
  [ 96 114 129]
  ...
  [159 167 177]
  [160 169 176]
  [159 167 175]]

 [[101 116 131]
  [102 117 133]
  [101 116 131]
  ...
  [162 170 180]
  [159 167 177]
  [162 170 180]]

 [[ 96 111 127]
  [ 99 115 130]
  [ 98 113 129]
  ...
  [159 167 177]
  [159 167 177]
  [161 169 179]]

 ...

 [[ 37  28  36]
  [ 37  28  36]
  [ 39  28  39]
  ...
  [ 42  34  58]
  [ 44  35  62]
  [ 44  35  62]]

 [[ 39  27  38]
  [ 39  27  38]
  [ 41  28  39]
  ...
  [ 42  35  56]
  [ 43  34  61]
  [ 43  34  61]]

 [[ 38  25  37]
  [ 39  27  38]
  [ 38  25  37]
  ...
  [ 43  37  56]
  [ 43  34  61]
  [ 45  36  63]]]
[[[ 98 115 130]
  [ 98 115 130]
  [ 98 115 130]
  ...
  [160 169 179]
  [160 168 178]
  [160 168 177]]

 [[ 99 114 129]
  [ 99 114 130]
  [ 98 114 128]
  ...
  [161 170 179]
  [160 168 178]
  [161 168 178]]

 [[101 114 129]
  [101 114 129]
  [100 114 129]
  ...
  [162 168 176]
  [163 169 177]
  [163 169 177]]

 ...

 [[ 42  30  40]
  [ 40  28  39]
  [ 35  25  36]
  ..

[[[ 94 111 128]
  [ 94 111 128]
  [ 95 113 128]
  ...
  [160 168 178]
  [162 167 178]
  [162 167 178]]

 [[ 97 111 130]
  [ 97 111 130]
  [ 99 114 132]
  ...
  [161 166 177]
  [160 169 176]
  [159 167 175]]

 [[ 97 111 130]
  [ 99 114 132]
  [103 117 135]
  ...
  [164 170 180]
  [159 167 175]
  [159 167 175]]

 ...

 [[ 39  27  38]
  [ 35  22  33]
  [ 40  30  39]
  ...
  [ 44  35  55]
  [ 45  35  57]
  [ 45  35  57]]

 [[ 37  24  35]
  [ 43  30  41]
  [ 39  27  38]
  ...
  [ 43  36  57]
  [ 44  35  62]
  [ 44  35  62]]

 [[ 36  27  35]
  [ 37  28  36]
  [ 37  28  36]
  ...
  [ 45  36  63]
  [ 42  36  62]
  [ 42  36  62]]]
[[[ 95 111 129]
  [ 96 113 129]
  [ 99 114 130]
  ...
  [161 168 178]
  [161 167 178]
  [161 167 177]]

 [[ 98 112 131]
  [100 115 133]
  [ 99 114 132]
  ...
  [162 167 177]
  [162 168 178]
  [159 167 175]]

 [[ 99 115 130]
  [ 98 114 130]
  [101 116 133]
  ...
  [161 168 176]
  [160 168 176]
  [160 169 176]]

 ...

 [[ 38  29  36]
  [ 37  28  35]
  [ 34  24  32]
  ..

[[[ 94 112 125]
  [ 96 115 128]
  [ 96 112 125]
  ...
  [159 167 175]
  [159 168 174]
  [159 168 174]]

 [[ 96 112 125]
  [ 97 113 126]
  [ 98 114 128]
  ...
  [159 168 174]
  [161 167 175]
  [161 167 175]]

 [[ 98 114 128]
  [ 98 114 128]
  [ 99 115 129]
  ...
  [159 167 175]
  [159 167 175]
  [158 166 174]]

 ...

 [[ 34  28  33]
  [ 35  29  35]
  [ 36  27  35]
  ...
  [ 43  34  61]
  [ 43  34  61]
  [ 44  35  62]]

 [[ 39  27  36]
  [ 38  26  35]
  [ 38  26  35]
  ...
  [ 40  33  59]
  [ 43  36  65]
  [ 42  35  63]]

 [[ 39  27  38]
  [ 38  25  37]
  [ 39  27  36]
  ...
  [ 42  36  62]
  [ 43  37  63]
  [ 42  36  62]]]
[[[ 95 113 126]
  [ 97 113 127]
  [ 98 114 127]
  ...
  [160 168 175]
  [159 168 175]
  [160 168 174]]

 [[ 97 113 127]
  [ 98 114 128]
  [ 99 115 129]
  ...
  [160 168 175]
  [159 167 175]
  [159 167 175]]

 [[ 97 113 127]
  [ 99 114 128]
  [ 99 114 129]
  ...
  [162 169 175]
  [162 169 175]
  [160 169 175]]

 ...

 [[ 37  31  38]
  [ 36  28  36]
  [ 30  21  29]
  ..

[[[ 97 113 126]
  [ 96 112 125]
  [ 95 113 126]
  ...
  [161 168 174]
  [161 167 175]
  [161 167 175]]

 [[104 117 131]
  [100 114 128]
  [ 99 115 129]
  ...
  [160 169 176]
  [162 168 176]
  [161 167 175]]

 [[ 94 110 123]
  [ 96 112 125]
  [ 97 112 128]
  ...
  [161 167 175]
  [159 167 175]
  [159 167 175]]

 ...

 [[ 36  26  37]
  [ 37  27  38]
  [ 37  27  38]
  ...
  [ 42  36  60]
  [ 43  35  59]
  [ 42  34  58]]

 [[ 33  22  33]
  [ 35  25  35]
  [ 36  23  34]
  ...
  [ 44  35  62]
  [ 44  35  62]
  [ 44  35  62]]

 [[ 36  23  34]
  [ 35  22  33]
  [ 37  27  38]
  ...
  [ 43  36  57]
  [ 42  34  58]
  [ 44  36  60]]]
[[[ 99 114 127]
  [ 97 113 127]
  [ 96 113 127]
  ...
  [161 168 175]
  [161 168 175]
  [161 167 175]]

 [[ 97 112 126]
  [ 98 113 128]
  [ 97 112 128]
  ...
  [161 169 176]
  [161 168 176]
  [160 167 175]]

 [[100 114 130]
  [101 115 131]
  [100 115 130]
  ...
  [161 168 176]
  [161 168 177]
  [161 168 177]]

 ...

 [[ 37  28  37]
  [ 39  29  39]
  [ 36  28  36]
  ..

[[[ 96 113 131]
  [ 94 111 128]
  [ 95 112 130]
  ...
  [159 167 175]
  [158 169 176]
  [157 168 175]]

 [[ 97 115 130]
  [ 96 114 129]
  [ 99 114 132]
  ...
  [159 167 175]
  [159 170 177]
  [158 169 176]]

 [[ 96 111 127]
  [ 97 112 128]
  [ 98 113 131]
  ...
  [160 169 176]
  [162 171 179]
  [161 170 177]]

 ...

 [[ 33  20  31]
  [ 35  22  33]
  [ 40  29  40]
  ...
  [ 40  32  54]
  [ 40  34  58]
  [ 41  35  59]]

 [[ 30  21  29]
  [ 33  23  32]
  [ 36  27  35]
  ...
  [ 42  35  56]
  [ 44  35  62]
  [ 45  36  63]]

 [[ 32  22  30]
  [ 33  23  32]
  [ 36  27  33]
  ...
  [ 45  37  61]
  [ 44  35  62]
  [ 44  35  62]]]
[[[ 96 113 130]
  [ 96 113 130]
  [ 98 114 132]
  ...
  [159 167 175]
  [159 168 175]
  [158 169 176]]

 [[ 97 112 128]
  [ 98 113 131]
  [102 116 134]
  ...
  [159 168 175]
  [160 169 176]
  [160 170 177]]

 [[ 98 113 128]
  [ 99 115 129]
  [100 116 130]
  ...
  [160 168 176]
  [161 169 176]
  [160 169 176]]

 ...

 [[ 38  26  38]
  [ 40  30  39]
  [ 38  28  37]
  ..

[[[ 98 114 128]
  [ 98 114 128]
  [ 98 114 128]
  ...
  [160 169 176]
  [160 169 176]
  [159 167 175]]

 [[ 92 108 122]
  [ 97 113 126]
  [ 97 113 126]
  ...
  [161 170 177]
  [160 169 176]
  [159 167 175]]

 [[ 97 113 126]
  [ 99 115 129]
  [ 99 115 129]
  ...
  [159 167 175]
  [159 167 175]
  [160 169 176]]

 ...

 [[ 34  24  34]
  [ 37  27  38]
  [ 39  28  39]
  ...
  [ 44  35  62]
  [ 46  35  62]
  [ 45  34  61]]

 [[ 39  27  38]
  [ 38  25  37]
  [ 38  25  37]
  ...
  [ 45  34  61]
  [ 47  36  63]
  [ 46  35  62]]

 [[ 36  23  34]
  [ 37  24  35]
  [ 37  24  35]
  ...
  [ 44  33  59]
  [ 45  37  61]
  [ 41  33  57]]]
[[[ 96 112 126]
  [ 98 114 127]
  [ 99 115 128]
  ...
  [160 169 176]
  [160 169 176]
  [159 168 175]]

 [[ 97 113 126]
  [ 98 114 128]
  [ 98 115 128]
  ...
  [160 169 176]
  [160 168 176]
  [160 168 176]]

 [[ 98 115 127]
  [ 99 115 128]
  [100 116 130]
  ...
  [160 170 176]
  [160 169 176]
  [159 169 176]]

 ...

 [[ 38  28  38]
  [ 38  29  38]
  [ 35  28  35]
  ..

[[[ 98 113 129]
  [ 97 112 128]
  [ 96 115 128]
  ...
  [159 167 177]
  [160 168 178]
  [160 168 178]]

 [[ 97 112 128]
  [ 99 115 130]
  [ 96 115 128]
  ...
  [159 167 175]
  [160 168 178]
  [161 169 179]]

 [[ 99 115 129]
  [ 98 114 128]
  [ 98 114 128]
  ...
  [159 167 175]
  [160 168 178]
  [159 167 177]]

 ...

 [[ 34  22  30]
  [ 36  24  33]
  [ 41  29  37]
  ...
  [ 45  35  57]
  [ 41  32  58]
  [ 44  35  62]]

 [[ 32  22  30]
  [ 34  24  33]
  [ 36  27  35]
  ...
  [ 44  35  55]
  [ 41  32  58]
  [ 44  35  62]]

 [[ 32  22  30]
  [ 34  24  33]
  [ 34  24  33]
  ...
  [ 44  37  59]
  [ 38  29  56]
  [ 43  34  61]]]
[[[ 98 113 129]
  [ 96 114 128]
  [ 96 115 127]
  ...
  [160 168 177]
  [159 167 177]
  [160 168 178]]

 [[ 98 114 129]
  [ 98 114 128]
  [ 98 114 128]
  ...
  [160 169 176]
  [159 168 176]
  [160 168 178]]

 [[ 98 113 129]
  [ 97 113 129]
  [ 98 115 130]
  ...
  [159 168 175]
  [160 169 176]
  [160 169 176]]

 ...

 [[ 37  24  34]
  [ 40  29  37]
  [ 38  28  35]
  ..

[[[ 96 113 124]
  [ 96 113 124]
  [ 97 113 126]
  ...
  [159 167 175]
  [159 167 175]
  [159 167 175]]

 [[101 112 126]
  [100 111 125]
  [ 98 112 125]
  ...
  [160 169 176]
  [160 169 176]
  [159 167 175]]

 [[ 99 114 123]
  [ 99 114 123]
  [102 114 126]
  ...
  [162 168 176]
  [162 168 176]
  [161 167 175]]

 ...

 [[ 35  25  34]
  [ 37  28  36]
  [ 41  31  40]
  ...
  [ 44  34  63]
  [ 40  31  64]
  [ 42  33  67]]

 [[ 34  24  34]
  [ 34  24  34]
  [ 32  22  30]
  ...
  [ 42  34  65]
  [ 40  34  67]
  [ 41  35  68]]

 [[ 35  27  38]
  [ 34  26  37]
  [ 35  27  38]
  ...
  [ 42  36  62]
  [ 41  34  62]
  [ 42  35  63]]]
[[[ 98 112 125]
  [ 97 112 125]
  [ 97 112 126]
  ...
  [160 167 175]
  [159 168 175]
  [159 167 175]]

 [[ 99 113 124]
  [101 113 125]
  [101 113 126]
  ...
  [162 168 176]
  [162 168 176]
  [161 168 175]]

 [[100 114 126]
  [101 113 127]
  [102 114 127]
  ...
  [162 170 176]
  [162 170 176]
  [161 169 175]]

 ...

 [[ 36  28  34]
  [ 38  29  36]
  [ 37  30  36]
  ..

[[[ 98 114 128]
  [101 117 130]
  [ 99 115 129]
  ...
  [161 168 174]
  [161 168 174]
  [161 168 174]]

 [[ 95 111 124]
  [ 99 115 129]
  [ 99 115 129]
  ...
  [161 170 177]
  [160 169 175]
  [159 168 174]]

 [[ 97 114 125]
  [ 99 116 127]
  [ 98 112 125]
  ...
  [162 171 179]
  [162 169 175]
  [161 168 174]]

 ...

 [[ 39  29  37]
  [ 39  29  37]
  [ 39  29  37]
  ...
  [ 44  35  62]
  [ 42  35  63]
  [ 42  35  63]]

 [[ 37  27  38]
  [ 41  30  41]
  [ 37  28  36]
  ...
  [ 42  35  63]
  [ 43  35  59]
  [ 42  34  58]]

 [[ 40  29  40]
  [ 40  29  40]
  [ 42  29  40]
  ...
  [ 42  31  56]
  [ 44  35  62]
  [ 44  35  62]]]
[[[ 98 114 128]
  [100 116 129]
  [ 99 116 129]
  ...
  [160 167 175]
  [161 169 175]
  [160 168 174]]

 [[ 98 114 126]
  [ 99 114 127]
  [101 115 128]
  ...
  [159 168 175]
  [161 170 177]
  [161 169 174]]

 [[ 99 114 127]
  [100 114 127]
  [100 114 128]
  ...
  [159 169 176]
  [160 171 177]
  [160 169 176]]

 ...

 [[ 40  30  38]
  [ 37  27  37]
  [ 32  20  30]
  ..

[[[ 96 113 128]
  [ 96 112 128]
  [ 97 112 128]
  ...
  [161 169 176]
  [161 169 176]
  [160 169 176]]

 [[ 99 114 129]
  [ 98 113 129]
  [100 115 130]
  ...
  [162 168 175]
  [162 169 176]
  [161 170 176]]

 [[100 114 128]
  [100 114 130]
  [102 115 131]
  ...
  [162 168 176]
  [163 169 176]
  [163 170 176]]

 ...

 [[ 37  28  34]
  [ 36  26  32]
  [ 31  21  27]
  ...
  [ 44  37  57]
  [ 42  35  57]
  [ 43  36  60]]

 [[ 38  29  36]
  [ 38  29  35]
  [ 33  24  31]
  ...
  [ 42  36  56]
  [ 42  36  58]
  [ 43  35  58]]

 [[ 37  28  36]
  [ 37  28  37]
  [ 34  23  32]
  ...
  [ 42  36  55]
  [ 42  36  57]
  [ 42  35  56]]]
[[[ 96 114 129]
  [ 94 111 127]
  [ 95 113 128]
  ...
  [160 169 176]
  [159 167 175]
  [160 169 176]]

 [[ 98 113 129]
  [ 96 111 127]
  [ 97 112 128]
  ...
  [163 169 177]
  [160 169 176]
  [160 169 176]]

 [[ 99 115 130]
  [ 99 115 130]
  [ 98 113 129]
  ...
  [162 168 176]
  [161 171 176]
  [160 169 175]]

 ...

 [[ 37  29  35]
  [ 39  30  36]
  [ 39  30  36]
  ..

[[[ 99 115 130]
  [ 99 115 130]
  [ 98 113 131]
  ...
  [159 167 175]
  [161 167 175]
  [161 167 175]]

 [[ 99 114 132]
  [101 115 133]
  [ 98 113 131]
  ...
  [160 169 176]
  [159 167 175]
  [159 167 175]]

 [[ 97 111 130]
  [ 96 110 128]
  [ 98 113 131]
  ...
  [159 167 175]
  [159 168 174]
  [159 168 174]]

 ...

 [[ 36  27  35]
  [ 36  27  35]
  [ 35  29  35]
  ...
  [ 38  32  51]
  [ 40  31  56]
  [ 40  31  56]]

 [[ 35  25  34]
  [ 36  27  35]
  [ 35  29  35]
  ...
  [ 42  33  51]
  [ 43  35  59]
  [ 42  34  58]]

 [[ 34  24  34]
  [ 37  27  38]
  [ 35  29  35]
  ...
  [ 45  35  57]
  [ 46  37  59]
  [ 43  33  55]]]
[[[ 99 115 131]
  [ 98 113 131]
  [ 97 111 129]
  ...
  [159 168 175]
  [160 167 175]
  [160 167 175]]

 [[ 98 112 130]
  [ 98 113 131]
  [ 99 113 131]
  ...
  [160 169 176]
  [159 168 175]
  [159 168 174]]

 [[100 114 130]
  [101 114 130]
  [102 114 130]
  ...
  [161 170 178]
  [160 168 175]
  [162 169 175]]

 ...

 [[ 40  30  38]
  [ 38  28  36]
  [ 34  25  34]
  ..

[[[ 97 113 126]
  [ 98 114 128]
  [ 97 112 128]
  ...
  [161 168 174]
  [161 168 174]
  [161 168 174]]

 [[ 98 114 128]
  [ 98 114 128]
  [ 95 110 126]
  ...
  [160 169 175]
  [162 168 176]
  [162 168 176]]

 [[101 114 130]
  [ 98 111 127]
  [ 99 112 128]
  ...
  [163 169 177]
  [161 170 177]
  [159 167 175]]

 ...

 [[ 39  27  38]
  [ 37  24  35]
  [ 37  28  36]
  ...
  [ 41  35  61]
  [ 42  36  62]
  [ 39  32  58]]

 [[ 38  26  35]
  [ 38  26  35]
  [ 37  28  36]
  ...
  [ 44  35  62]
  [ 42  36  62]
  [ 40  33  59]]

 [[ 36  23  34]
  [ 36  23  34]
  [ 39  27  38]
  ...
  [ 44  35  62]
  [ 45  36  63]
  [ 40  31  57]]]
[[[ 98 114 127]
  [ 97 112 127]
  [ 96 113 128]
  ...
  [160 168 174]
  [161 168 174]
  [161 168 175]]

 [[ 99 113 128]
  [ 98 112 128]
  [ 98 112 128]
  ...
  [161 168 175]
  [162 169 176]
  [160 168 176]]

 [[100 114 127]
  [ 99 112 127]
  [ 99 112 126]
  ...
  [162 169 175]
  [161 169 175]
  [160 168 174]]

 ...

 [[ 40  29  36]
  [ 39  30  36]
  [ 36  26  34]
  ..

[[[ 96 112 125]
  [ 98 114 128]
  [ 99 115 129]
  ...
  [160 169 176]
  [160 169 176]
  [159 167 175]]

 [[100 114 128]
  [103 116 130]
  [101 115 129]
  ...
  [162 168 176]
  [159 167 175]
  [159 167 175]]

 [[ 97 110 124]
  [ 97 110 124]
  [ 98 112 125]
  ...
  [162 168 176]
  [162 168 176]
  [162 168 176]]

 ...

 [[ 39  27  36]
  [ 41  29  37]
  [ 42  29  40]
  ...
  [ 43  34  61]
  [ 42  33  59]
  [ 44  35  62]]

 [[ 38  25  37]
  [ 36  23  34]
  [ 39  27  38]
  ...
  [ 38  29  56]
  [ 43  34  61]
  [ 44  35  62]]

 [[ 37  28  36]
  [ 37  28  36]
  [ 42  29  40]
  ...
  [ 43  32  57]
  [ 44  35  62]
  [ 44  35  62]]]
[[[ 98 114 127]
  [100 115 129]
  [ 99 114 128]
  ...
  [160 167 175]
  [160 168 176]
  [159 167 175]]

 [[ 99 112 126]
  [ 99 113 127]
  [100 114 129]
  ...
  [162 168 175]
  [162 168 176]
  [161 168 176]]

 [[101 114 129]
  [101 114 130]
  [101 114 130]
  ...
  [162 169 173]
  [161 169 173]
  [162 169 175]]

 ...

 [[ 41  29  38]
  [ 42  30  39]
  [ 37  25  34]
  ..

[[[ 99 113 126]
  [ 99 113 126]
  [101 115 129]
  ...
  [160 169 176]
  [161 170 177]
  [160 169 176]]

 [[ 97 110 124]
  [ 98 112 125]
  [101 114 130]
  ...
  [160 166 174]
  [161 168 174]
  [160 167 172]]

 [[ 98 111 127]
  [ 98 111 127]
  [101 116 131]
  ...
  [162 168 176]
  [160 166 174]
  [162 168 176]]

 ...

 [[ 37  27  38]
  [ 37  27  38]
  [ 39  27  36]
  ...
  [ 42  33  59]
  [ 43  37  63]
  [ 42  36  62]]

 [[ 39  27  36]
  [ 39  27  36]
  [ 37  28  36]
  ...
  [ 42  35  63]
  [ 45  36  67]
  [ 42  34  65]]

 [[ 38  27  33]
  [ 36  25  31]
  [ 37  29  35]
  ...
  [ 42  35  63]
  [ 41  36  66]
  [ 40  34  65]]]
[[[ 98 112 125]
  [100 114 128]
  [ 98 112 127]
  ...
  [161 167 176]
  [160 168 175]
  [160 169 175]]

 [[ 98 111 126]
  [100 114 129]
  [ 98 112 128]
  ...
  [162 168 176]
  [161 167 175]
  [161 167 175]]

 [[ 99 113 126]
  [100 116 131]
  [100 116 131]
  ...
  [160 169 176]
  [160 168 176]
  [161 167 175]]

 ...

 [[ 38  28  36]
  [ 37  27  35]
  [ 36  25  34]
  ..

[[[ 96 111 127]
  [ 98 113 129]
  [ 96 114 129]
  ...
  [159 167 175]
  [160 169 176]
  [160 169 176]]

 [[ 97 113 126]
  [101 117 130]
  [ 97 112 128]
  ...
  [159 167 175]
  [159 167 175]
  [160 169 176]]

 [[ 99 117 130]
  [100 118 131]
  [101 118 134]
  ...
  [160 169 176]
  [159 167 177]
  [159 167 177]]

 ...

 [[ 36  24  33]
  [ 38  26  35]
  [ 40  31  37]
  ...
  [ 42  35  56]
  [ 42  34  58]
  [ 42  34  58]]

 [[ 36  27  35]
  [ 35  25  34]
  [ 38  31  37]
  ...
  [ 43  37  56]
  [ 43  37  56]
  [ 43  37  56]]

 [[ 35  25  34]
  [ 35  25  34]
  [ 37  28  36]
  ...
  [ 44  37  59]
  [ 44  38  57]
  [ 44  38  57]]]
[[[ 97 113 128]
  [ 97 114 129]
  [ 98 114 130]
  ...
  [159 168 175]
  [159 167 175]
  [160 169 176]]

 [[ 99 117 130]
  [100 117 132]
  [ 98 114 130]
  ...
  [160 169 176]
  [160 168 176]
  [159 168 177]]

 [[101 116 130]
  [102 116 132]
  [102 117 133]
  ...
  [162 168 176]
  [161 168 176]
  [160 170 176]]

 ...

 [[ 38  27  35]
  [ 36  27  33]
  [ 33  24  30]
  ..

[[[ 98 112 125]
  [ 98 112 125]
  [ 99 115 129]
  ...
  [160 168 178]
  [160 169 176]
  [159 167 175]]

 [[ 99 113 125]
  [ 99 113 125]
  [ 96 113 124]
  ...
  [161 170 177]
  [160 169 176]
  [161 170 177]]

 [[101 112 126]
  [102 113 128]
  [101 115 129]
  ...
  [160 169 176]
  [160 169 176]
  [160 169 176]]

 ...

 [[ 36  27  35]
  [ 37  28  36]
  [ 34  27  35]
  ...
  [ 42  36  62]
  [ 41  35  61]
  [ 41  35  61]]

 [[ 34  24  33]
  [ 36  27  35]
  [ 37  28  36]
  ...
  [ 42  36  60]
  [ 42  35  63]
  [ 42  35  63]]

 [[ 34  24  34]
  [ 37  27  38]
  [ 37  27  38]
  ...
  [ 42  34  58]
  [ 45  36  63]
  [ 45  36  63]]]
[[[ 98 112 125]
  [ 98 114 127]
  [ 98 115 130]
  ...
  [159 168 177]
  [160 169 177]
  [160 168 176]]

 [[101 113 126]
  [100 114 127]
  [100 115 128]
  ...
  [160 168 176]
  [160 169 176]
  [160 169 176]]

 [[102 113 127]
  [101 115 129]
  [100 114 128]
  ...
  [160 167 174]
  [161 168 175]
  [162 169 175]]

 ...

 [[ 38  30  37]
  [ 38  30  38]
  [ 36  28  38]
  ..

[[[ 99 115 130]
  [ 99 115 130]
  [ 96 111 127]
  ...
  [160 169 176]
  [159 167 175]
  [159 167 175]]

 [[ 99 115 130]
  [ 98 113 129]
  [ 98 113 129]
  ...
  [160 169 176]
  [157 168 175]
  [157 168 175]]

 [[101 117 130]
  [ 99 115 129]
  [ 96 113 124]
  ...
  [160 169 176]
  [158 166 174]
  [160 169 176]]

 ...

 [[ 36  23  34]
  [ 37  24  35]
  [ 38  26  35]
  ...
  [ 43  35  59]
  [ 43  35  59]
  [ 42  34  58]]

 [[ 35  23  32]
  [ 39  27  36]
  [ 37  28  36]
  ...
  [ 45  37  66]
  [ 43  35  66]
  [ 43  35  66]]

 [[ 38  25  37]
  [ 37  24  35]
  [ 39  27  38]
  ...
  [ 45  36  63]
  [ 48  39  65]
  [ 43  34  61]]]
[[[ 99 115 130]
  [ 97 112 128]
  [ 98 113 129]
  ...
  [160 169 176]
  [159 168 176]
  [158 167 175]]

 [[ 99 116 129]
  [ 97 114 127]
  [ 98 114 128]
  ...
  [161 170 177]
  [160 169 176]
  [159 168 175]]

 [[ 97 115 129]
  [ 97 116 129]
  [ 97 115 128]
  ...
  [160 169 176]
  [159 168 175]
  [160 168 176]]

 ...

 [[ 38  27  34]
  [ 38  27  34]
  [ 38  28  36]
  ..

[[[ 99 115 130]
  [ 98 113 129]
  [ 96 111 127]
  ...
  [159 167 175]
  [161 167 175]
  [161 167 175]]

 [[ 98 113 129]
  [ 99 115 130]
  [ 99 112 128]
  ...
  [159 167 175]
  [159 168 174]
  [159 168 174]]

 [[ 98 113 129]
  [ 99 115 130]
  [101 114 130]
  ...
  [160 169 176]
  [161 170 177]
  [160 169 176]]

 ...

 [[ 41  28  39]
  [ 39  27  38]
  [ 39  27  38]
  ...
  [ 38  33  52]
  [ 45  36  63]
  [ 43  34  61]]

 [[ 36  27  33]
  [ 37  29  35]
  [ 40  30  39]
  ...
  [ 41  35  52]
  [ 44  35  62]
  [ 43  34  61]]

 [[ 37  24  35]
  [ 38  25  37]
  [ 37  28  36]
  ...
  [ 38  33  50]
  [ 43  35  59]
  [ 42  34  58]]]
[[[ 99 114 130]
  [ 98 112 128]
  [ 99 112 128]
  ...
  [160 168 176]
  [159 167 175]
  [160 167 175]]

 [[ 99 114 129]
  [100 114 129]
  [ 99 113 128]
  ...
  [160 168 176]
  [160 169 176]
  [160 169 176]]

 [[100 115 128]
  [101 115 130]
  [102 116 131]
  ...
  [161 170 176]
  [160 169 176]
  [160 168 176]]

 ...

 [[ 38  29  38]
  [ 39  28  38]
  [ 38  26  38]
  ..

[[[ 98 114 128]
  [ 98 114 128]
  [ 95 113 128]
  ...
  [159 167 175]
  [159 167 175]
  [159 167 175]]

 [[ 97 113 126]
  [ 98 114 128]
  [ 96 115 128]
  ...
  [162 171 179]
  [162 171 179]
  [160 169 176]]

 [[100 114 128]
  [ 99 113 126]
  [ 97 113 126]
  ...
  [160 169 176]
  [161 170 177]
  [160 169 176]]

 ...

 [[ 41  28  39]
  [ 39  27  38]
  [ 39  27  38]
  ...
  [ 42  35  63]
  [ 42  33  67]
  [ 42  33  67]]

 [[ 39  27  38]
  [ 41  28  39]
  [ 41  28  39]
  ...
  [ 44  35  62]
  [ 42  36  62]
  [ 41  35  61]]

 [[ 39  27  38]
  [ 39  27  38]
  [ 39  27  38]
  ...
  [ 42  35  56]
  [ 43  36  65]
  [ 43  36  65]]]
[[[ 98 114 128]
  [ 96 114 128]
  [ 96 113 128]
  ...
  [160 168 176]
  [160 169 177]
  [160 168 176]]

 [[ 99 114 127]
  [ 98 114 127]
  [ 99 115 129]
  ...
  [160 169 176]
  [161 170 177]
  [161 169 176]]

 [[102 114 129]
  [102 115 128]
  [102 116 129]
  ...
  [160 168 174]
  [162 170 176]
  [162 170 176]]

 ...

 [[ 38  28  38]
  [ 39  29  38]
  [ 36  25  35]
  ..

[[[ 98 113 129]
  [ 96 111 127]
  [ 98 113 129]
  ...
  [161 167 175]
  [161 167 175]
  [162 168 176]]

 [[ 98 113 129]
  [ 98 113 129]
  [ 98 113 129]
  ...
  [159 167 175]
  [162 168 176]
  [161 167 175]]

 [[ 98 114 128]
  [ 99 115 129]
  [ 97 112 128]
  ...
  [160 169 176]
  [160 169 176]
  [159 167 175]]

 ...

 [[ 39  29  37]
  [ 37  28  36]
  [ 34  27  35]
  ...
  [ 44  36  60]
  [ 44  37  59]
  [ 42  35  56]]

 [[ 37  27  38]
  [ 40  29  40]
  [ 35  28  36]
  ...
  [ 42  35  56]
  [ 42  36  60]
  [ 41  35  59]]

 [[ 36  26  37]
  [ 37  27  38]
  [ 31  24  32]
  ...
  [ 44  36  60]
  [ 47  38  71]
  [ 46  37  70]]]
[[[ 98 113 129]
  [ 98 113 129]
  [ 97 113 129]
  ...
  [160 167 175]
  [161 167 175]
  [162 168 176]]

 [[ 98 114 129]
  [ 98 113 128]
  [ 97 114 129]
  ...
  [161 168 176]
  [160 169 176]
  [160 168 175]]

 [[100 115 129]
  [ 99 114 128]
  [101 115 130]
  ...
  [162 168 176]
  [163 169 177]
  [162 168 176]]

 ...

 [[ 38  29  37]
  [ 35  28  36]
  [ 33  26  34]
  ..

[[[ 98 111 127]
  [ 98 111 127]
  [ 99 115 130]
  ...
  [160 168 178]
  [162 167 178]
  [161 166 177]]

 [[ 96 111 127]
  [ 96 111 127]
  [ 97 115 130]
  ...
  [163 169 177]
  [162 168 176]
  [162 168 176]]

 [[ 97 113 126]
  [ 99 115 129]
  [ 99 115 130]
  ...
  [159 167 175]
  [162 167 178]
  [162 167 178]]

 ...

 [[ 39  27  36]
  [ 39  27  36]
  [ 37  29  35]
  ...
  [ 44  35  62]
  [ 42  35  63]
  [ 42  35  63]]

 [[ 36  27  35]
  [ 37  28  36]
  [ 37  28  36]
  ...
  [ 39  29  53]
  [ 40  30  59]
  [ 43  33  62]]

 [[ 36  27  35]
  [ 36  27  35]
  [ 35  29  35]
  ...
  [ 44  35  62]
  [ 41  32  58]
  [ 44  35  62]]]
[[[ 97 111 127]
  [ 98 114 129]
  [ 96 113 129]
  ...
  [160 168 176]
  [161 168 177]
  [162 167 177]]

 [[ 98 113 127]
  [ 99 115 129]
  [ 98 114 129]
  ...
  [161 167 175]
  [161 168 176]
  [162 167 177]]

 [[100 114 127]
  [101 115 129]
  [102 116 130]
  ...
  [161 168 175]
  [161 169 175]
  [161 169 176]]

 ...

 [[ 41  29  38]
  [ 37  26  35]
  [ 35  24  32]
  ..

[[[ 96 112 125]
  [ 97 113 126]
  [ 95 113 126]
  ...
  [161 168 174]
  [161 168 174]
  [162 169 175]]

 [[ 95 113 126]
  [ 95 113 126]
  [ 96 112 125]
  ...
  [161 168 174]
  [159 168 174]
  [160 169 175]]

 [[ 97 113 126]
  [ 98 114 128]
  [ 97 113 126]
  ...
  [160 169 175]
  [160 169 175]
  [160 169 175]]

 ...

 [[ 35  25  34]
  [ 35  25  34]
  [ 39  30  36]
  ...
  [ 44  35  62]
  [ 45  36  65]
  [ 48  38  67]]

 [[ 36  27  35]
  [ 35  25  34]
  [ 39  29  37]
  ...
  [ 44  36  60]
  [ 44  35  62]
  [ 43  34  61]]

 [[ 34  24  33]
  [ 34  24  33]
  [ 37  28  36]
  ...
  [ 42  36  60]
  [ 44  37  59]
  [ 41  33  55]]]
[[[ 96 113 126]
  [ 96 113 126]
  [ 97 113 127]
  ...
  [161 168 174]
  [161 168 174]
  [161 169 175]]

 [[ 97 114 127]
  [ 97 114 127]
  [ 98 114 126]
  ...
  [161 169 175]
  [160 169 175]
  [160 169 175]]

 [[100 115 130]
  [100 116 130]
  [100 115 129]
  ...
  [161 169 175]
  [163 170 176]
  [162 169 174]]

 ...

 [[ 34  25  31]
  [ 36  26  33]
  [ 37  28  34]
  ..

[[[ 99 113 125]
  [100 115 126]
  [ 99 113 125]
  ...
  [161 167 175]
  [161 168 174]
  [161 168 174]]

 [[101 115 129]
  [100 114 128]
  [101 116 127]
  ...
  [161 168 174]
  [162 169 175]
  [161 168 174]]

 [[101 115 129]
  [101 115 129]
  [101 116 127]
  ...
  [161 168 174]
  [161 168 174]
  [162 169 175]]

 ...

 [[ 35  25  34]
  [ 37  28  36]
  [ 39  29  37]
  ...
  [ 41  33  55]
  [ 43  34  61]
  [ 43  34  61]]

 [[ 33  23  32]
  [ 37  28  36]
  [ 37  28  36]
  ...
  [ 42  35  56]
  [ 41  33  57]
  [ 43  35  59]]

 [[ 32  25  33]
  [ 34  27  35]
  [ 36  27  35]
  ...
  [ 43  34  54]
  [ 43  36  57]
  [ 43  36  57]]]
[[[100 114 127]
  [100 114 126]
  [ 98 113 125]
  ...
  [160 167 174]
  [161 168 174]
  [161 168 174]]

 [[101 115 129]
  [101 116 128]
  [ 99 115 126]
  ...
  [161 168 174]
  [161 168 174]
  [161 169 175]]

 [[101 114 128]
  [100 114 128]
  [100 114 128]
  ...
  [162 169 175]
  [161 170 175]
  [160 169 175]]

 ...

 [[ 38  29  36]
  [ 37  28  35]
  [ 38  29  36]
  ..

[[[ 96 112 125]
  [ 96 112 125]
  [ 97 112 128]
  ...
  [159 167 175]
  [159 167 175]
  [159 167 175]]

 [[ 99 112 128]
  [ 99 112 128]
  [ 99 115 130]
  ...
  [160 169 176]
  [160 169 176]
  [159 167 175]]

 [[ 98 113 129]
  [ 98 113 129]
  [100 113 129]
  ...
  [160 169 175]
  [159 167 175]
  [159 167 175]]

 ...

 [[ 37  27  38]
  [ 37  27  38]
  [ 37  28  36]
  ...
  [ 45  38  64]
  [ 44  38  57]
  [ 38  32  51]]

 [[ 35  25  35]
  [ 37  27  38]
  [ 37  28  36]
  ...
  [ 45  37  66]
  [ 45  38  60]
  [ 42  35  56]]

 [[ 30  20  31]
  [ 35  25  35]
  [ 40  29  40]
  ...
  [ 44  35  62]
  [ 44  34  63]
  [ 48  38  67]]]
[[[ 97 112 126]
  [ 98 113 128]
  [ 98 113 128]
  ...
  [160 169 176]
  [159 168 175]
  [159 167 175]]

 [[ 98 113 129]
  [ 99 114 129]
  [100 115 129]
  ...
  [161 170 176]
  [160 169 175]
  [159 167 175]]

 [[ 99 113 129]
  [101 116 131]
  [100 116 130]
  ...
  [162 169 176]
  [162 168 175]
  [161 169 175]]

 ...

 [[ 36  28  36]
  [ 37  28  37]
  [ 38  28  38]
  ..

[[[ 97 112 128]
  [ 98 113 129]
  [ 95 113 128]
  ...
  [161 167 175]
  [161 168 174]
  [160 167 172]]

 [[ 99 115 130]
  [101 116 131]
  [ 96 114 129]
  ...
  [161 167 175]
  [161 168 174]
  [160 167 172]]

 [[ 97 112 128]
  [ 99 115 130]
  [ 98 113 129]
  ...
  [162 168 176]
  [161 168 174]
  [161 168 174]]

 ...

 [[ 37  28  36]
  [ 37  28  36]
  [ 37  28  36]
  ...
  [ 44  35  62]
  [ 40  31  56]
  [ 42  34  58]]

 [[ 36  26  37]
  [ 36  26  37]
  [ 37  27  38]
  ...
  [ 42  34  58]
  [ 42  33  59]
  [ 43  34  61]]

 [[ 34  24  33]
  [ 36  27  35]
  [ 40  29  40]
  ...
  [ 40  31  56]
  [ 45  36  63]
  [ 43  34  61]]]
[[[ 98 114 129]
  [ 96 113 129]
  [ 96 113 129]
  ...
  [161 167 175]
  [161 167 175]
  [160 167 173]]

 [[ 99 114 129]
  [ 98 114 129]
  [101 116 131]
  ...
  [161 168 175]
  [161 168 175]
  [161 168 174]]

 [[100 113 129]
  [100 114 130]
  [100 114 129]
  ...
  [160 168 175]
  [161 168 176]
  [161 168 175]]

 ...

 [[ 38  29  36]
  [ 38  28  36]
  [ 35  26  34]
  ..

[[[ 97 113 126]
  [ 98 114 128]
  [ 98 113 129]
  ...
  [162 167 178]
  [160 169 176]
  [159 167 175]]

 [[ 98 112 125]
  [101 115 129]
  [ 99 115 130]
  ...
  [160 169 176]
  [160 169 176]
  [159 167 175]]

 [[ 99 112 128]
  [103 115 131]
  [ 96 111 127]
  ...
  [161 170 177]
  [160 169 176]
  [158 166 174]]

 ...

 [[ 37  28  36]
  [ 36  27  35]
  [ 35  29  35]
  ...
  [ 42  36  62]
  [ 42  36  62]
  [ 41  35  61]]

 [[ 33  26  34]
  [ 32  25  33]
  [ 35  29  35]
  ...
  [ 42  36  60]
  [ 42  34  58]
  [ 44  36  60]]

 [[ 35  25  34]
  [ 34  24  33]
  [ 34  28  33]
  ...
  [ 43  35  59]
  [ 41  35  61]
  [ 42  36  62]]]
[[[ 98 113 127]
  [ 98 114 129]
  [ 98 113 129]
  ...
  [161 167 176]
  [161 168 177]
  [159 168 175]]

 [[100 113 129]
  [ 98 113 129]
  [ 99 114 129]
  ...
  [160 168 176]
  [161 169 177]
  [159 167 175]]

 [[100 115 130]
  [100 115 131]
  [100 115 130]
  ...
  [162 168 176]
  [162 169 177]
  [161 169 176]]

 ...

 [[ 39  28  38]
  [ 38  28  38]
  [ 37  27  38]
  ..

[[[ 96 114 129]
  [ 96 114 129]
  [ 95 113 128]
  ...
  [159 167 175]
  [159 167 175]
  [159 167 175]]

 [[ 96 114 129]
  [ 97 115 130]
  [ 97 115 130]
  ...
  [160 169 176]
  [161 167 175]
  [161 167 175]]

 [[ 99 115 130]
  [ 99 115 130]
  [ 99 115 130]
  ...
  [160 169 176]
  [161 170 177]
  [160 169 176]]

 ...

 [[ 39  27  38]
  [ 38  25  37]
  [ 39  27  38]
  ...
  [ 40  31  56]
  [ 44  35  62]
  [ 44  35  62]]

 [[ 37  27  38]
  [ 39  28  39]
  [ 37  27  38]
  ...
  [ 40  33  52]
  [ 44  36  60]
  [ 42  34  58]]

 [[ 34  28  33]
  [ 34  28  33]
  [ 33  27  32]
  ...
  [ 43  37  63]
  [ 45  38  60]
  [ 40  32  54]]]
[[[ 96 114 129]
  [ 96 114 129]
  [ 97 114 128]
  ...
  [160 168 176]
  [160 168 175]
  [160 167 175]]

 [[ 99 115 130]
  [ 99 115 130]
  [ 99 114 129]
  ...
  [160 168 175]
  [160 169 176]
  [161 169 176]]

 [[ 99 114 128]
  [100 114 128]
  [100 114 128]
  ...
  [160 169 176]
  [160 168 174]
  [161 168 174]]

 ...

 [[ 38  29  36]
  [ 35  27  34]
  [ 36  28  34]
  ..

[[[ 96 112 125]
  [ 97 113 126]
  [ 99 115 129]
  ...
  [161 168 173]
  [161 168 174]
  [162 169 175]]

 [[ 96 113 128]
  [ 96 114 129]
  [ 96 114 130]
  ...
  [161 168 174]
  [162 169 175]
  [161 168 174]]

 [[ 97 115 130]
  [ 97 115 130]
  [ 98 116 131]
  ...
  [161 168 174]
  [162 169 175]
  [162 169 175]]

 ...

 [[ 37  28  34]
  [ 36  28  34]
  [ 38  28  34]
  ...
  [ 42  33  56]
  [ 43  33  60]
  [ 43  34  62]]

 [[ 36  27  33]
  [ 37  29  34]
  [ 37  28  34]
  ...
  [ 43  36  59]
  [ 43  35  61]
  [ 43  33  62]]

 [[ 34  25  31]
  [ 36  28  33]
  [ 37  29  35]
  ...
  [ 43  36  57]
  [ 44  36  61]
  [ 44  34  62]]]
[[[ 95 111 124]
  [ 96 112 125]
  [ 97 113 126]
  ...
  [161 168 174]
  [162 169 175]
  [164 171 177]]

 [[ 96 112 125]
  [ 97 113 126]
  [ 97 113 126]
  ...
  [162 169 175]
  [162 169 175]
  [158 166 171]]

 [[ 94 111 127]
  [ 97 115 130]
  [ 94 114 129]
  ...
  [162 169 175]
  [161 168 174]
  [161 168 174]]

 ...

 [[ 35  26  32]
  [ 37  29  35]
  [ 37  29  35]
  ..

[[[101 115 129]
  [ 99 113 126]
  [103 116 130]
  ...
  [159 167 175]
  [159 167 177]
  [159 167 177]]

 [[ 99 112 128]
  [100 113 129]
  [100 113 129]
  ...
  [161 170 177]
  [160 169 176]
  [159 167 175]]

 [[ 98 112 125]
  [101 115 129]
  [100 114 128]
  ...
  [161 170 177]
  [161 167 175]
  [162 168 176]]

 ...

 [[ 41  28  39]
  [ 45  32  44]
  [ 42  30  39]
  ...
  [ 43  35  59]
  [ 42  34  58]
  [ 42  34  58]]

 [[ 38  25  37]
  [ 36  23  34]
  [ 34  24  33]
  ...
  [ 43  36  57]
  [ 41  33  57]
  [ 40  31  56]]

 [[ 38  26  35]
  [ 37  25  34]
  [ 39  28  35]
  ...
  [ 43  34  61]
  [ 43  34  61]
  [ 42  33  59]]]
[[[100 114 128]
  [101 114 129]
  [ 99 113 128]
  ...
  [160 168 175]
  [160 168 176]
  [159 167 176]]

 [[ 99 113 127]
  [100 114 128]
  [ 99 113 126]
  ...
  [159 168 175]
  [161 169 176]
  [161 168 175]]

 [[100 114 129]
  [101 115 129]
  [101 115 128]
  ...
  [160 168 176]
  [161 169 176]
  [160 168 175]]

 ...

 [[ 39  28  37]
  [ 40  30  38]
  [ 36  26  33]
  ..

[[[ 98 114 128]
  [ 98 114 128]
  [ 96 111 127]
  ...
  [159 167 175]
  [158 169 176]
  [157 168 175]]

 [[ 97 113 126]
  [ 96 112 125]
  [ 97 112 128]
  ...
  [159 167 175]
  [159 167 175]
  [159 167 175]]

 [[ 99 115 129]
  [ 99 115 129]
  [ 99 115 129]
  ...
  [159 167 177]
  [157 168 175]
  [157 168 175]]

 ...

 [[ 37  28  36]
  [ 37  28  36]
  [ 37  28  36]
  ...
  [ 44  35  62]
  [ 41  34  62]
  [ 42  35  63]]

 [[ 37  28  36]
  [ 36  27  35]
  [ 37  27  38]
  ...
  [ 43  35  59]
  [ 42  36  62]
  [ 42  36  62]]

 [[ 34  22  30]
  [ 31  19  28]
  [ 37  24  35]
  ...
  [ 43  35  59]
  [ 44  36  60]
  [ 43  35  59]]]
[[[ 97 113 127]
  [ 97 112 127]
  [ 98 113 128]
  ...
  [159 166 176]
  [159 167 175]
  [158 168 175]]

 [[ 99 114 128]
  [ 98 114 128]
  [ 98 114 128]
  ...
  [161 168 178]
  [159 168 176]
  [158 168 175]]

 [[100 113 129]
  [100 114 129]
  [102 116 130]
  ...
  [161 168 176]
  [161 169 176]
  [160 168 177]]

 ...

 [[ 38  30  38]
  [ 38  30  38]
  [ 35  28  36]
  ..

[[[ 96 111 127]
  [ 97 112 128]
  [ 96 111 127]
  ...
  [158 166 174]
  [159 167 175]
  [159 167 175]]

 [[ 98 111 127]
  [ 99 112 128]
  [101 114 130]
  ...
  [158 167 172]
  [159 167 175]
  [159 167 175]]

 [[ 97 110 126]
  [ 98 111 127]
  [100 113 129]
  ...
  [161 168 174]
  [159 168 174]
  [160 169 175]]

 ...

 [[ 36  26  37]
  [ 37  27  38]
  [ 37  29  37]
  ...
  [ 42  34  58]
  [ 41  35  61]
  [ 39  32  58]]

 [[ 38  25  37]
  [ 41  28  39]
  [ 40  30  39]
  ...
  [ 43  35  59]
  [ 42  36  62]
  [ 41  35  61]]

 [[ 35  25  35]
  [ 29  19  30]
  [ 37  27  38]
  ...
  [ 42  35  56]
  [ 42  36  62]
  [ 42  36  62]]]
[[[ 97 111 127]
  [ 98 112 128]
  [ 97 112 128]
  ...
  [160 168 174]
  [158 167 174]
  [159 167 175]]

 [[ 98 111 127]
  [100 113 129]
  [ 98 112 128]
  ...
  [161 168 174]
  [160 168 174]
  [160 168 175]]

 [[101 114 130]
  [101 114 130]
  [ 97 112 128]
  ...
  [161 169 173]
  [161 169 175]
  [160 169 175]]

 ...

 [[ 39  29  39]
  [ 38  28  38]
  [ 36  26  36]
  ..

[[[ 97 114 125]
  [ 98 115 126]
  [ 99 115 129]
  ...
  [159 167 175]
  [161 167 175]
  [160 166 174]]

 [[ 98 114 128]
  [ 97 113 126]
  [ 96 115 128]
  ...
  [161 171 176]
  [160 169 176]
  [159 167 175]]

 [[ 97 112 128]
  [ 99 115 130]
  [ 97 115 130]
  ...
  [161 170 177]
  [161 171 176]
  [159 168 174]]

 ...

 [[ 35  29  35]
  [ 34  28  33]
  [ 37  29  35]
  ...
  [ 42  33  59]
  [ 40  33  59]
  [ 42  36  62]]

 [[ 36  26  37]
  [ 36  26  37]
  [ 40  29  40]
  ...
  [ 41  34  54]
  [ 43  34  61]
  [ 44  35  62]]

 [[ 37  27  38]
  [ 37  27  38]
  [ 41  29  37]
  ...
  [ 44  36  60]
  [ 42  35  63]
  [ 43  36  65]]]
[[[ 97 114 126]
  [ 97 114 127]
  [ 96 113 127]
  ...
  [160 168 176]
  [160 168 175]
  [160 167 175]]

 [[ 98 114 128]
  [ 97 115 129]
  [ 95 113 128]
  ...
  [161 170 176]
  [161 170 176]
  [160 169 175]]

 [[ 99 115 127]
  [ 98 115 128]
  [ 98 115 129]
  ...
  [160 168 175]
  [160 169 176]
  [159 168 175]]

 ...

 [[ 40  30  38]
  [ 36  28  36]
  [ 36  27  36]
  ..

[[[ 99 113 126]
  [ 98 112 125]
  [100 114 128]
  ...
  [160 169 176]
  [159 167 175]
  [159 167 175]]

 [[ 99 112 128]
  [100 113 129]
  [100 113 129]
  ...
  [160 169 176]
  [160 169 176]
  [159 167 175]]

 [[ 92 108 123]
  [101 116 131]
  [ 99 115 130]
  ...
  [159 167 175]
  [160 169 176]
  [155 164 172]]

 ...

 [[ 35  25  34]
  [ 36  27  35]
  [ 39  29  37]
  ...
  [ 44  33  58]
  [ 43  34  61]
  [ 44  35  62]]

 [[ 37  28  36]
  [ 37  28  36]
  [ 36  27  35]
  ...
  [ 44  33  58]
  [ 42  33  59]
  [ 44  35  62]]

 [[ 36  27  35]
  [ 34  24  33]
  [ 40  30  39]
  ...
  [ 43  34  54]
  [ 44  35  62]
  [ 47  38  64]]]
[[[ 99 113 127]
  [100 113 128]
  [ 98 113 128]
  ...
  [160 168 176]
  [160 169 176]
  [159 167 175]]

 [[ 97 112 127]
  [100 115 130]
  [ 98 114 130]
  ...
  [160 169 176]
  [160 168 176]
  [158 167 174]]

 [[102 114 130]
  [102 114 130]
  [100 114 130]
  ...
  [160 168 176]
  [160 168 176]
  [159 168 175]]

 ...

 [[ 42  30  41]
  [ 41  29  39]
  [ 36  25  35]
  ..

[[[ 98 111 127]
  [ 94 107 123]
  [ 96 112 125]
  ...
  [159 167 175]
  [159 167 175]
  [159 167 175]]

 [[ 99 112 128]
  [ 98 111 127]
  [101 116 131]
  ...
  [161 168 174]
  [159 167 175]
  [159 167 175]]

 [[ 98 112 125]
  [100 114 128]
  [ 99 115 130]
  ...
  [161 167 175]
  [160 169 176]
  [160 169 176]]

 ...

 [[ 35  29  35]
  [ 35  29  35]
  [ 36  27  35]
  ...
  [ 44  35  62]
  [ 43  32  64]
  [ 43  32  64]]

 [[ 37  29  35]
  [ 42  33  39]
  [ 41  29  37]
  ...
  [ 43  34  61]
  [ 44  35  62]
  [ 42  33  59]]

 [[ 39  27  36]
  [ 37  25  34]
  [ 39  30  36]
  ...
  [ 44  35  62]
  [ 45  36  63]
  [ 44  35  62]]]
[[[ 97 110 126]
  [ 97 112 126]
  [ 97 113 128]
  ...
  [161 168 176]
  [160 167 175]
  [159 167 175]]

 [[ 99 113 127]
  [ 99 114 129]
  [ 97 113 128]
  ...
  [161 168 175]
  [161 168 175]
  [160 168 176]]

 [[100 115 129]
  [ 99 115 129]
  [100 115 130]
  ...
  [161 167 175]
  [161 167 175]
  [160 167 175]]

 ...

 [[ 38  31  38]
  [ 37  29  35]
  [ 34  24  31]
  ..

[[[ 97 112 128]
  [ 98 113 129]
  [ 99 114 132]
  ...
  [161 167 175]
  [160 169 176]
  [160 169 176]]

 [[ 99 115 130]
  [ 98 113 129]
  [ 95 113 128]
  ...
  [160 169 176]
  [160 169 176]
  [159 167 175]]

 [[ 97 115 130]
  [ 95 113 128]
  [ 91 106 122]
  ...
  [159 167 175]
  [161 170 177]
  [159 167 175]]

 ...

 [[ 37  27  38]
  [ 37  27  38]
  [ 35  29  35]
  ...
  [ 43  37  56]
  [ 43  34  61]
  [ 45  36  63]]

 [[ 38  25  37]
  [ 38  25  37]
  [ 39  28  35]
  ...
  [ 41  36  57]
  [ 42  36  62]
  [ 42  36  62]]

 [[ 37  24  35]
  [ 37  24  35]
  [ 39  27  38]
  ...
  [ 44  36  60]
  [ 43  37  63]
  [ 42  36  62]]]
[[[ 98 113 129]
  [ 98 113 130]
  [ 96 113 131]
  ...
  [160 167 175]
  [160 168 176]
  [160 169 176]]

 [[ 97 114 129]
  [ 94 110 126]
  [ 99 115 132]
  ...
  [160 168 176]
  [160 168 176]
  [160 168 176]]

 [[ 98 115 127]
  [ 98 114 128]
  [100 116 131]
  ...
  [159 169 175]
  [159 169 176]
  [160 168 176]]

 ...

 [[ 39  29  37]
  [ 38  29  37]
  [ 37  28  37]
  ..

[[[ 99 114 130]
  [ 97 113 129]
  [ 96 113 127]
  ...
  [160 168 176]
  [160 168 175]
  [161 168 175]]

 [[ 98 113 129]
  [ 98 113 129]
  [ 98 115 129]
  ...
  [162 168 175]
  [161 168 174]
  [161 168 173]]

 [[101 115 130]
  [ 99 113 128]
  [102 116 131]
  ...
  [161 168 174]
  [162 169 175]
  [161 168 174]]

 ...

 [[ 41  28  39]
  [ 37  24  35]
  [ 31  20  31]
  ...
  [ 42  36  59]
  [ 42  35  61]
  [ 44  35  64]]

 [[ 36  27  38]
  [ 34  26  37]
  [ 29  21  32]
  ...
  [ 43  37  60]
  [ 42  36  59]
  [ 41  32  59]]

 [[ 36  27  38]
  [ 35  28  38]
  [ 32  24  35]
  ...
  [ 44  37  60]
  [ 44  36  59]
  [ 43  36  59]]]
[[[101 116 131]
  [ 96 111 127]
  [ 98 113 129]
  ...
  [160 169 176]
  [162 168 176]
  [161 167 175]]

 [[ 99 115 130]
  [ 98 113 129]
  [ 96 114 129]
  ...
  [160 167 172]
  [161 168 174]
  [161 168 174]]

 [[ 97 112 128]
  [ 98 113 129]
  [ 98 113 129]
  ...
  [162 169 175]
  [161 168 174]
  [160 167 172]]

 ...

 [[ 35  27  38]
  [ 35  27  38]
  [ 35  27  38]
  ..

[[[ 97 112 126]
  [ 97 112 128]
  [ 98 113 129]
  ...
  [160 167 176]
  [161 167 177]
  [162 168 176]]

 [[ 99 112 128]
  [ 98 113 129]
  [ 99 114 130]
  ...
  [161 167 176]
  [162 168 176]
  [162 168 176]]

 [[100 115 131]
  [ 99 114 130]
  [ 99 114 130]
  ...
  [160 168 176]
  [162 169 177]
  [163 169 177]]

 ...

 [[ 36  28  34]
  [ 36  25  33]
  [ 29  17  26]
  ...
  [ 42  36  58]
  [ 42  37  58]
  [ 40  35  57]]

 [[ 36  26  34]
  [ 37  25  34]
  [ 32  19  29]
  ...
  [ 43  37  56]
  [ 41  35  57]
  [ 42  34  58]]

 [[ 37  27  36]
  [ 35  24  35]
  [ 32  21  32]
  ...
  [ 43  35  56]
  [ 43  34  58]
  [ 42  34  58]]]
[[[ 96 113 131]
  [ 94 111 128]
  [ 96 114 129]
  ...
  [161 168 174]
  [161 168 174]
  [161 168 174]]

 [[ 99 115 130]
  [ 98 113 129]
  [ 98 113 129]
  ...
  [159 167 175]
  [159 167 175]
  [159 167 175]]

 [[ 97 111 130]
  [ 99 114 132]
  [ 99 114 132]
  ...
  [157 169 174]
  [159 168 174]
  [159 168 174]]

 ...

 [[ 37  29  37]
  [ 35  28  36]
  [ 39  27  38]
  ..

[[[ 99 114 129]
  [ 99 114 128]
  [ 98 115 129]
  ...
  [160 168 174]
  [160 168 175]
  [160 168 176]]

 [[100 114 128]
  [ 99 113 127]
  [100 114 128]
  ...
  [160 169 176]
  [160 168 176]
  [160 169 176]]

 [[100 114 128]
  [100 114 128]
  [101 115 130]
  ...
  [159 170 176]
  [159 169 175]
  [160 168 176]]

 ...

 [[ 36  28  34]
  [ 35  27  33]
  [ 30  20  26]
  ...
  [ 43  36  56]
  [ 42  35  55]
  [ 42  34  55]]

 [[ 37  30  36]
  [ 36  29  36]
  [ 33  24  30]
  ...
  [ 44  37  56]
  [ 44  36  56]
  [ 44  35  56]]

 [[ 38  29  37]
  [ 35  28  35]
  [ 32  24  31]
  ...
  [ 41  34  54]
  [ 42  35  56]
  [ 42  35  56]]]
[[[ 96 111 127]
  [ 96 111 127]
  [ 98 113 129]
  ...
  [161 168 174]
  [159 167 175]
  [159 167 175]]

 [[ 96 111 127]
  [ 99 115 130]
  [101 116 131]
  ...
  [161 168 174]
  [161 168 174]
  [161 168 174]]

 [[100 113 129]
  [103 115 131]
  [101 116 131]
  ...
  [162 169 175]
  [161 168 174]
  [161 168 174]]

 ...

 [[ 40  30  39]
  [ 39  29  37]
  [ 37  27  38]
  ..

In [3]:
# do a bit of cleanup
cv2.destroyAllWindows()
vs.stop()